# Generated by Django 4.2.7 on 2026-05-03 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaSecreta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('ativa', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pergunta Secreta',
                'verbose_name_plural': 'Perguntas Secretas',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TentativaRecuperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('tentativas', models.IntegerField(default=0)),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_recuperacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentativa de Recuperação',
                'verbose_name_plural': 'Tentativas de Recuperação',
            },
        ),
        migrations.CreateModel(
            name='LogTentativaSuspeita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('acao', models.CharField(max_length=100)),
                ('detalhes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_suspeitos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Tentativa Suspeita',
                'verbose_name_plural': 'Logs de Tentativas Suspeitas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RespostaSecreta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_hash', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.perguntasecreta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_secretas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resposta Secreta',
                'verbose_name_plural': 'Respostas Secretas',
                'unique_together': {('user', 'pergunta')},
            },
        ),
    ]
